global:
  domain: ""
  limitsEnabled: true
  dataPartitionId: ""

data:
  #Configmaps
  entitlementsHost: "http://entitlements"
  javaOptions: "-Xms512M -Xmx1024M -XX:+UseG1GC -XX:+UseStringDeduplication -XX:InitiatingHeapOccupancyPercent=45"
  logLevel: "ERROR"
  partitionHost: "http://partition"
  schemaTopicName: "schema-changed"
  schemaChangedMessagingEnabled: true
  enableCleanup: false
  schemaHost: "http://schema"
  #Deployments
  requestsCpu: "220m"
  requestsMemory: "1.7G"
  limitsCpu: "1"
  limitsMemory: "2.5G"
  bootstrapImage: ""
  bootstrapServiceAccountName: ""
  image: ""
  imagePullPolicy: "IfNotPresent"
  serviceAccountName: "schema"

conf:
  appName: "schema"
  bootstrapSecretName: "datafier-secret"
  configmap: "schema-config"
  minioSecretName: "schema-minio-secret"
  schemaS3SecretName: "schema-seaweedfs-secret"
  postgresSecretName: "schema-postgres-secret"
  rabbitmqSecretName: "rabbitmq-secret"
  replicas: 1

istio:
  proxyCPU: "90m"
  proxyCPULimit: "500m"
  proxyMemory: "100Mi"
  proxyMemoryLimit: "512Mi"
  bootstrapProxyCPU: "10m"
  bootstrapProxyCPULimit: "100m"
