package org.opengroup.osdu.schema.constants;

public class TestConstants {
    public static final String FORWARD_SLASH = "/";
    public static final String PUT_ENDPOINT = "/api/schema-service/v1/schemas/system";
    public static final String POST_ENDPOINT = "/api/schema-service/v1/schema";
    public static final String GET_LIST_ENDPOINT = "/api/schema-service/v1/schema";
    public static final String GET_ENDPOINT = "/api/schema-service/v1/schema/";
    public static final String GET_FLATTENED_ENDPOINT = "/api/schema-service/v1/schema/{id}/IndexerSchemaV1";
    public static final String GET_INFO_ENDPOINT = "/api/schema-service/v1/info";
    //public static final String HOST = "http://localhost:8080";
    public static final String INTERNAL_SERVER_ERROR = "internal server error";
    public static final String INTERNAL = "INTERNAL";
    public static final String SCHEMA_KIND = "schema";
    public static final String AUTHORITY = "authority";
    public static final String LATEST_VERSION = "latestVersion";
    public static final String GET_SUCCESSRESPONSECODE = "200";
    public static final String SOURCE = "source";
    public static final String ENTITY_TYPE = "entityType";
    public static final String MAJOR_VERSION = "majorVersion";
    public static final String MINOR_VERSION = "minorVersion";
    public static final String PATCH_VERSION = "patchVersion";
    public static final String CREATED_BY = "createdBy";
    public static final String SUPERSEDED_BY = "supersededBy";
    public static final String DATE_CREATED = "dateCreated";
    public static final String SCHEMA = "schema";
    public static final String OBSOLETE = "OBSOLETE";
    public static final String PUBLISHED = "PUBLISHED";
    public static final String SCOPE = "scope";
    public static final String STATUS = "status";
    public static final String ALREADY_EXISTS = "ALREADY_EXISTS";
    public static final String DATAECOSYSTEM = "dataecosystem";
    public static final String AUTHORIZATION = "authorization";
    public static final String DATA_PARTITION_ID = "data-partition-id";
    public static final String BEARER = "Bearer ";
    public static final String CONTENT_TYPE = "Content-Type";
    public static final String JSON_CONTENT = "application/json";
    public static final String schemaIdOfInputPayload = "schemaInfo.schemaIdentity.id";
    public static final String SCHEMA_IDENTITY = "schemaIdentity";
    public static final String ENTITY = "entityType";
    public static final String SCHEMA_MAJOR_VERSION = "schemaVersionMajor";
    public static final String SCHEMA_MINOR_VERSION = "schemaVersionMinor";
    public static final String SCHEMA_PATCH_VERSION = "schemaVersionPatch";
    public static final String ID = "id";
    public static final String DOT = ".";
    public static final String ERROR = "error";
    public static final String MESSAGE = "message";
    public static final String STORAGE_SCHEMA = "StorageSchema";
    public static final String USER = "user";
    public static final String STORAGE_SCHEMA_USER_EMAIL = "testUserEmail@test.com";
    public static final String KIND = "kind";
    public static final String TRUE = "true";
    public static final String HOST = System.getProperty("HOST", System.getenv("HOST"));
    public static final String PRIVATE_TENANT1 = System.getProperty("PRIVATE_TENANT1", System.getenv("PRIVATE_TENANT1"));
    public static final String PRIVATE_TENANT2 = System.getProperty("PRIVATE_TENANT2", System.getenv("PRIVATE_TENANT2"));
    public static final String SHARED_TENANT = System.getProperty("SHARED_TENANT", System.getenv("SHARED_TENANT"));
    public static final String SYSTEM_TENANT = System.getProperty("SYSTEM_TENANT", System.getenv("SYSTEM_TENANT"));
    public static final Integer HTTP_RETRY_COUNT_DEFAULT = 3;
    public static final Integer HTTP_RETRY_COUNT = System.getenv("HTTP_RETRY_COUNT")!=null ? Integer.parseInt(System.getenv("HTTP_RETRY_COUNT")) : HTTP_RETRY_COUNT_DEFAULT ;
    public static final Long HTTP_RETRY_BACKOFF_MILLIS_DEFAULT = 1000L;
    public static final Long HTTP_RETRY_BACKOFF_MILLIS = System.getenv("HTTP_RETRY_BACKOFF")!=null ? Long.parseLong(System.getenv("HTTP_RETRY_BACKOFF")) : HTTP_RETRY_BACKOFF_MILLIS_DEFAULT ;
}
