azure_test:
  image: community.opengroup.org:5555/osdu/platform/deployment-and-operations/base-containers-azure/azure-maven17:v0.0.1
  script:
  - cd $AZURE_TEST_SUBDIR
  - mvn clean verify -DdisableXmlReport=true

azure-clean-test-schemas:
  tags: ["osdu-medium"]
  image: curlimages/curl
  stage: clean
  script:
  - echo "deleting test schemas.."
  - curl -v --location --request POST 'https://osdu-glab.msft-osdu-test.org/api/schema-cleanup-service/v1/schemas' 
